steps:
- name: node
  entrypoint: npm
  args:
  - 'install'
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'us-docker.pkg.dev/cloudrun/container/hello'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY


